# 配置邮件
MAIL_SERVER = 'smtp.163.com'
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_DEBUG = True
MAIL_USERNAME = "lu_0523@163.com"
MAIL_PASSWORD = "NCFLMESPHRXRKPQG"
MAIL_DEFAULT_SENDER = "lu_0523@163.com"
MAIL_MAX_EMAILS = None
MAIL_ASCII_ATTACHMENTS = False
